# Generated by Django 3.2.3 on 2023-11-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231108_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
